### ISSUE TITLE
Clicking Sign Up sends multiple emails

### ISSUE THREAD

**Issue by CharlBest** [CriticalMoments/CMSaasStarter#30] opened 2024-03-11 19:33 UTC
Clicking the sign up button will send multiple requests/emails. This is probably the case for "forgot password" as well. 

<img width="1260" alt="image" src="https://github.com/CriticalMoments/CMSaasStarter/assets/6147400/08b8c6ce-3afd-4b46-90eb-70f059767c1c">

Possible solutions:
- disable the button after you click it with a 1 minute re-activation
- indefinitely disable button (until refresh)
- button is still clickable but in the background, debounce and don't send another request within x seconds

**Comment by scosman** [comment] 2024-03-11 21:06
Can you add repo steps? I'm only getting 1 email.

**Comment by CharlBest** [comment] 2024-03-11 21:22
1. I deleted my account
2. Went to `https://saasstarter.work/login/sign_up/`
3. Typed in my email and password
4. Click on SIGN UP, wait +- 3 seconds
5. Click on SIGN UP 3 more times with 1 second intervals

<img width="377" alt="image" src="https://github.com/CriticalMoments/CMSaasStarter/assets/6147400/a3f565c1-bb71-46d7-b9df-90703a285944">
<img width="1278" alt="image" src="https://github.com/CriticalMoments/CMSaasStarter/assets/6147400/1d1e4c00-955f-43ea-95f6-7e988a1639c8">

Browser: Chrome

**Comment by scosman** [comment] 2024-03-11 21:48
Ah, it re-enables after it's complete! 

is this not a but in supabase/auth-helpers? They handle all this UI.

**Comment by CharlBest** [comment] 2024-03-11 23:05
I haven't looked into the [auth-ui](https://github.com/supabase-community/auth-ui) library so much, just assumed it would have events you can hook into and do things accordingly like show a different UI while it's loading but doesn't seem like that is the case. 

Saw it went into `[Maintenance Mode](https://github.com/supabase-community/auth-ui)` about a month ago. That's very sad 😭 Rather than maintaining framework-specific packages, they should just have a standard/native html/js package.

<img width="844" alt="image" src="https://github.com/CriticalMoments/CMSaasStarter/assets/6147400/72e2b1b5-5af5-40c3-ae89-b294cbb4219b">

**Comment by owenversteeg** [comment] 2024-03-12 00:42
Hmm, not sure this should be closed, the issue still exists even if `auth-ui` is in "maintenance mode". I suppose this is another reason to migrate to SSR from auth-helpers?

**Comment by scosman** [comment] 2024-03-13 02:01
Duplicate of #29 

Back and forth on this one 🤣. But we don’t need 2 issues for same action item. If the upgrade to ssr is the fix, let’s track that in 29. If it’s not let’s file a bug on supabase because it’s on their side.

**Closed by scosman** 2024-03-13 02:01 UTC
